// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nini-date/NiniDateInvitation.tsx": () => import("../components/mockups/nini-date/NiniDateInvitation.tsx")
};
